name: Tungsten
services:
    tungsten:
        container_name: tungsten
        build: .
        environment:
            - AUTH_SECRET=${AUTH_SECRET}
            - AUTH_URL=${AUTH_URL}
            - ALLOW_SIGNUPS=${ALLOW_SIGNUPS}
            - IMAGE_MAX_SIZE=${IMAGE_MAX_SIZE}
        volumes:
            - db:/app/data/
        env_file: ".env"
volumes:
    db:
