name: Tungsten
services:
    tungsten:
        container_name: tungsten
        ports:
            - 3000:3000
        environment:
            - AUTH_SECRET=${AUTH_SECRET}
            - AUTH_URL=${AUTH_URL}
            - ALLOW_SIGNUPS=${ALLOW_SIGNUPS}
        env_file: ".env"
        image: ghcr.io/mrdiamonddog/tungsten:master
